homeassistant:
  # 系统名称，金窝银窝随便取
  name: 家
  # 经纬度设置
  latitude: xxxxxx
  longitude: xxxxx
  # 海拔
  elevation: 11
  # 度量单位，这里选择“米”
  unit_system: metric
  # 时区
  time_zone: Asia/Shanghai
  # 设备昵称
  customize: !include customize.yaml

# introduction:

#自定义 UI
customizer:
  custom_ui: local

# 前端开启
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

# http 服务
http:
  api_password: !secret http_password
  trusted_networks: 
    - 127.0.0.1
    - ::1
    - 192.168.50.0/24


# 开启更新检测，默认关闭，需要开启请取消备注
# updater:

# 开启自动设备探测
discovery:

# ios设备，可获取电量及充电信息
ios:

# 开启语音指令
#conversation:

# 历史记录
history:

# 事件log
logbook:

# 追踪日出日落
sun:

# 语音合成
tts:
  - platform: baidu
    language: zh
    api_key: !secret baidu_apikey
    secret_key: !secret baidu_key
    speed: 5
    pitch: 5
    volume: 5
    person: 1
    
# 小米平台
xiaomi_aqara:
  gateways:
      - mac: F0B429B43088
        key: !secret xiaomi_key

# yeelight



# 设备追踪
device_tracker:
  - platform: asuswrt
    host: 192.168.50.1
    username: admin
    password: !secret router_password
    protocol: telnet
    track_new_devices: no
    interval_seconds: 60

# IFTTT
ifttt:
  key: !secret ifttt_key

# 自定义传感器
sensor:
#潮汐
#  - platform: command_line
#    name: Tide
#    command: "python3 /home/pi/Downloads/tide.py" 
#月相
  - platform: moon
  - platform: template
    sensors:
      moon_state:
        value_template: '{% if is_state("sersor.moon", "New moon") %}新月{% elif is_state("sersor.moon", "Waxing crescent") %}娥眉月{% elif is_state("sersor.moon", "First quarter") %}上弦月{% elif is_state("sersor.moon", "Waxing gibbous") %}盈凸月{% elif is_state("sersor.moon", "Full moon") %}满月{% elif is_state("sersor.moon", "Waning gibbous") %}亏凸月{% elif is_state("sersor.moon", "Last quarter") %}下弦月{% else %}残月{% endif %}'
        friendly_name: '月亮'
#太阳 
  - platform: template
    sensors:
      sun_state:
        value_template: '{% if is_state("sun.sun", "above_horizon") %}日出{% else %}日落{% endif %}'
        friendly_name: '太阳'
#植物监测仪
  - platform: miflora
    mac: 'C4:7C:8D:64:DD:98'
    name: coconut
    force_update: true
    median: 2
#PS4游戏
  - platform: template
    sensors:
      games:
        value_template: '{% if states.media_player.playstation_4 %}{{ states.media_player.playstation_4.attributes.source }}{% else %}无{% endif %}'
        friendly_name: '游戏名'

#空气质量
  - platform: airvisual
    api_key: mvMXuYS9SAuSmrsuq
    monitored_conditions:
      - us
      - cn
    radius: 500

  - platform: template
    sensors:
      air_index:
        value_template: '{% if is_state("sensor.chinese_air_pollution_level", "Good") %}优{% elif is_state("sensor.chinese_air_pollution_level", "Moderate") %}中等{% elif is_state("sensor.chinese_air_pollution_level", "Unhealthy for Sensitive Groups") %}轻度污染{% elif is_state("sensor.chinese_air_pollution_level", "Unhealthy") %}不健康{% elif is_state("sensor.chinese_air_pollution_level", "Very Unhealthy") %}极不健康{% else %}有毒害{% endif %}'
        friendly_name: '空气质量等级'
#季节
  - platform: season
    type: meteorological

  - platform: template
    sensors:
      seasons:
        value_template: '{% if is_state("sensor.season", "Spring") %}春季{% elif is_state("sensor.season", "Summer") %}夏季{% elif is_state("sensor.season", "Autumn") %}秋季{% else %}冬季{% endif %}'
        friendly_name: '季节'
        icon_template: >
          {% if is_state("sensor.season", "Spring") %}
            mdi:leaf
          {% elif is_state("sensor.season", "Summer") %}
            mdi:beach
          {% elif is_state("sensor.season", "Autumn") %}
            mdi:weather-windy-variant
          {% else %}
            mdi:snowflake
          {% endif %}

#PS4
media_player:
  - platform: ps4
    host: 192.168.50.25

  - platform: vlc
    name: speaker_1
    arguments: '--alsa-audio-device=hw:0,1'


# 盆栽状态
binary_sensor:
  - platform: template
    sensors:
      plant_moisture:
        value_template: '{{ states.sensor.coconut_moisture.state | float <= 20 }}'
        friendly_name: '湿度状态'
  - platform: template
    sensors:
      plant_fertility:
        value_template: '{{ states.sensor.coconut_conductivity.state | float <= 300 }}'
        friendly_name: '肥力状态'
  - platform: template
    sensors:
      co:
        friendly_name: '花'
        device_class: 'motion'
        value_template: >-
          {%- if is_state("binary_sensor.plant_moisture", "off")
              and is_state("binary_sensor.plant_fertility", "off") -%}
          False
          {%- else -%}
          True
          {%- endif -%}

#空调伴侣
climate:
  - platform: mi_acpartner
    name: mi_acpartner
    host: 192.168.50.236
    token: !secret ac_token
    target_temp: 26
    target_sensor: sensor.temperature_158d00010e50d7

#Todoist
#calendar:
#  - platform: todoist
#    token: !secret todoist_token
#    custom_projects:
#      - name: 'This week'
#        due_date_days: 7


#高德地图
#camera:
#  name: Home
#  platform: generic
#  still_image_url: http://restapi.amap.com/v3/staticmap?location=xxxx,xxxx&zoom=14&scale=2&size=305*185&traffic=1&&labels=家,0,0,35,0xFFFFFF,0x5288d8:xxx,xx&key=xxxxxxxxxxxxx
#  limit_refetch_to_url_change: false

# 群组管理
group: !include groups.yaml

# 场景
scene:
  - name: sleep
    entities:
      group.all_lights: off
  - name: exit
    entities:
      group.all_lights: off
      group.all_switches: off
      media_player.playstation_4: off

# 自定义 panel,此为 Floorplan
panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

#自动化
automation: !include automations.yaml

#人脸识别
microsoft_face:
  api_key: !secret microsoft_key
  azure_region: westcentralus